RIA-6394 - added S2S authentication (ServiceAuthorization) to update payment status request
hmcts/ia-case-payments-api pull request #291
Opened 2023-07-25 13:57 UTC by burnstHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RIA-6394

### Change description ###
As per the email from Maya Spence (See attached to the JIRA ticket), this PR is to add S2S authentication via the 'ServiceAuthorization' header on the payment status update request in ia-case-payments-api, as well as including the 'payment_app' service name to the idam.s2s-authorised.services property for use within the authorisation logic.

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

2023-07-26 10:26 UTC, filippo-possenti-version1 requested changes
As discussed in our code review session, make sure the changes we did during the session work and add an integration test for the controller as well.

2023-07-27 13:38 UTC, filippo-possenti-version1 approved these changes

2023-10-06 11:51 UTC, apereverzin1 submitted a review, later dismissed

2023-10-06 11:51 UTC, apereverzin1 commented
Added also integration tests for failure

2023-10-10 09:40 UTC, nilay913 submitted a review, later dismissed
LGTM

2024-01-10 13:32 UTC, KleoG approved these changes

2024-02-07 10:08 UTC, alivenichoppa approved these changes

2024-02-12 16:03 UTC, merged